// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIO5u8iO6PVuyGuHFWO__uhSuIZfQO3fA',
    appId: '1:673049855841:web:fbcf9663636dc7614ba720',
    messagingSenderId: '673049855841',
    projectId: 'women-safety-6090d',
    authDomain: 'women-safety-6090d.firebaseapp.com',
    storageBucket: 'women-safety-6090d.firebasestorage.app',
    measurementId: 'G-T17MBZ424N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnqmUvxXU7XNSEq0oMhu5PGfcjmYeyL3s',
    appId: '1:673049855841:android:da195eab76e373ac4ba720',
    messagingSenderId: '673049855841',
    projectId: 'women-safety-6090d',
    storageBucket: 'women-safety-6090d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIO5u8iO6PVuyGuHFWO__uhSuIZfQO3fA',
    appId: '1:673049855841:web:96f0af495a2c82b64ba720',
    messagingSenderId: '673049855841',
    projectId: 'women-safety-6090d',
    authDomain: 'women-safety-6090d.firebaseapp.com',
    storageBucket: 'women-safety-6090d.firebasestorage.app',
    measurementId: 'G-MRV7E47NY2',
  );

}